### PR TITLE
Add compatibility with OTP 24

### LINKED ISSUE #35: Functions such as :crypto.block_encrypt will be deprecated
In http://erlang.org/doc/apps/crypto/new_api.html it is recommended that the "new API", with functions such as `crypto_one_time/4`, be used over the "old API", with functions such as `block_encrypt/4`. The old functions might be deprecated in the future.

`ex_crypto` uses the old API in its implementations of the `encrypt` function, for example.

### PR DESCRIPTION
**Pull request by lukaszsamson**
Fixes #35

### CODE REVIEW

**Comment by ntrepid8** [comment]
Thanks! I'll get this merged and upload a new version to hex.pm in the next day or so.

**Comment by nicnilov** [comment]
Is this waiting for something in order to be pushed to hex.pm?

**Comment by wpr101** [comment]
> Is this waiting for something in order to be pushed to hex.pm?

Also wondering if this has been released? I'm seeing the same error occur after upgrading my application to Elixir 1.12 and OTP 24.

**Comment by wpr101** [comment]
> Thanks! I'll get this merged and upload a new version to hex.pm in the next day or so.

Hi ntrepid8, checking if you are able to release the code to hex.pm? 

I'm showing the last release on hex.pm as being 0.10.0 Feb 20, 2019

**Comment by johnspens** [comment]
Hi @nicnilov. Any update on a release to hex.pm?

**Comment by nicnilov** [comment]
@johnspens That's a question to @ntrepid8.

**Comment by leland-rasmussen** [comment]
HI @ntrepid8 any update on publishing to hex?

**Comment by bymayanksingh** [comment]
Hey @ntrepid8, are you planning to release this to hex?

**Pull request merged**
