### PR TITLE
Misc doc changes

### PR DESCRIPTION
**Pull request by kianmeng**
Besides other documentation changes, this commit ensures the generated
HTML doc for HexDocs.pm will become the main source doc for this Elixir
library which leverage on latest ExDoc features.

Screenshot:

Screenshot-20210407205600-2684x1464

### CODE REVIEW

**Comment by kianmeng** [comment]
@ntrepid8 Should I resolve the conflict and resubmit again?

**Comment by ntrepid8** [comment]
Yeah, if you can resolve the conflict then I can review and merge it.

**Comment by kianmeng** [comment]
@ntrepid8 Done. Please check.

**Comment by kianmeng** [comment]
:tada: :tada: :tada: :tada: :tada:

**Pull request merged**
