### PR TITLE
Add generate_key and pem_encode wrappers

### PR DESCRIPTION
**Pull request by barttenbrinke**
Hi, I was working with encryption and saw that these to methods from the Erlang PublicKey module where not wrapped, so I added them.

Great work so far!

### CODE REVIEW

**Comment by ntrepid8** [comment]
Looks great! Thanks for the PR, not sure why Travis hasn't finished the tests yet but if it's still hung up in a little bit I'll poke it and get it running.

**Comment by barttenbrinke** [comment]
I’ll rebase it first thing tomorrow!

**Comment by barttenbrinke** [comment]
I've rebased it, so it should merge cleanly with master.

**Comment by ntrepid8** [comment]
I'm still not sure why Travis is not running the tests. I've emailed their support to see if they can help. When I look at the [request logs](https://travis-ci.org/ntrepid8/ex_crypto/requests) I see this:

selection_348

@barttenbrinke ever had anything like this happen before with Travis?

**Comment by barttenbrinke** [comment]
No, but my guess is that generating ssh keys might be an abuse indicator.

**Comment by ntrepid8** [comment]
Not sure why that would be considered abuse. Openssl is a fairly standard thing to use. These tests don't put much strain on the entropy pool or on the CPU. It's not like we are consuming hundreds of MBs of entropy or something.

**Comment by barttenbrinke** [comment]
No, but there are people making prs on opensource projects to mine things like bitcoins. And generating ssh keys might Therfore be flagged.

**Comment by ntrepid8** [comment]
Perhaps, but I would think it would trigger more frequently on this project if that were the case. This is the first time I've seen it, but `¯\_(ツ)_/¯`

**Comment by ntrepid8** [comment]
I'm going to close this and re-open it to try and re-trigger the Travis build. I just got an email from them saying they have fixed the false-positive.

**Comment by ntrepid8** [comment]
Re-opening...

**Comment by ntrepid8** [comment]
trying again...

**Comment by ntrepid8** [comment]
Cool, Travis ran the build correctly this time :)

It does seem like some tests are failing though: https://travis-ci.org/ntrepid8/ex_crypto/builds/292262872

Seeing anything like that when you run the tests locally?

**Comment by barttenbrinke** [comment]
Well yesterday it was all green, let me look at it :)

**Comment by barttenbrinke** [comment]
@ntrepid8 So the core issue was that Travis was building against otp 18, and there are a lot of crypto changes on otp20 (which I am running). I've bumped the Erlang dependency to 20 and also updated elxir to 1.4.5 (lowest version that supports otp20). I also added some module and method docs to the ExPublicKey module, so that the exdoc is now a bit more usefull.

**Comment by barttenbrinke** [comment]
After this is merged, you are getting a PR where all methods/moduels have a basic ex_doc, because I can't stand the docs being as empty as they are :)

**Comment by ntrepid8** [comment]
One issue is that requiring a library like this to run the latest OTP creates a lot of issues for projects that use it. I even have some other projects with requirements that are not compatible with OTP 20. I would very much like to avoid making OTP 20 an absolute requirement.

Which crypto change are you bumping up against? Perhaps there is a way that we can support the new features w/o breaking backward compatibility to OTP 18.

**Comment by ntrepid8** [comment]
Also, any documentation help is always appreciated :)

**Comment by barttenbrinke** [comment]
I think we need to support both 18 and 20.. we can do something like 

: :application.get_key(:crypto, :vsn)

And then call the function with the correct parameters.

And then let Travis test that? I can build that tomorrow.

**Comment by ntrepid8** [comment]
Sounds good.

**Comment by barttenbrinke** [comment]
According to jose valim we should call if :application.get_key(:crypto, :vsn)  at runtime and use that to either call A or B.

**Comment by barttenbrinke** [comment]
Turns out OTP < 20 has no rsa keygen support, so I'll try falling back to openssl when needed..

**Comment by barttenbrinke** [comment]
@ntrepid8 I think this is the best I can do.

**Comment by barttenbrinke** [comment]
Or we could just return an :unsupported atom, like excrypto does.

**Comment by ntrepid8** [comment]
Sweet, thanks! I'll take a look today and try to get it released.

**Comment by barttenbrinke** [comment]
👍 That was interesting :)

**Comment by ntrepid8** [comment]
I'll get this released today on hex.pm as v0.7.0

**Comment by ntrepid8** [comment]
published as 0.7.0: https://hex.pm/packages/ex_crypto/0.7.0

**Pull request merged**
